language: common-lisp

env:
  matrix:
    - LISP=sbcl COVERALLS=true
    - LISP=ccl
    - LISP=clisp
    - LISP=ecl
    - LISP=abcl

install:
  - curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | sh;
  - git clone https://github.com/fukamachi/cl-coveralls

#before-_script:
#  - git clone https://github.com/fukamachi/cl-coveralls

script:
  - cl -l prove -l cl-slug -l cl-coveralls
       -e '(setf prove:*debug-on-error* t
                 *debugger-hook* (lambda (c h)
                                   (declare (ignore c h))
                                   (uiop:quit -1)))'
       -e '(or (coveralls:with-coveralls (:exclude "t")
                 (prove:run :cl-slug-test))
               (uiop:quit -1))'
